### PR TITLE
Replace 'mount -l' with 'findmnt'

### PR DESCRIPTION
**Pull request by jaromil**
This fixes a mount-related functionality (finding the volume label) in new versions of util-linux, that since v2.30 does not list anymore volume labels with its mount -l command. Since findmnt needs sudo to list labels, this also introduces the need for sudo in more commands: is_valid_tomb(), list, index and search. The issue was examined in PR #283 and this is a rebase of it.

### CODE REVIEW

**Comment by jaromil** [comment]
Waiting for tests and last minute reviews, then will rebase my fixes in one single commit and merge this.

**Comment by Narrat** [comment]
What I don't like is the increased usage of sudo. Especially since the first approach in the other PR would have worked for me :D Too bad findmnt works totally different between versions (or distribution specific patches are to blame, dunno).
But yeah, using findmnt is cleaner.
Didn't take a look yet at your additional changes

**Comment by Narrat** [comment]
Any issues without the square parens detection, or what is the rationale for going back?

**Comment by calvertvl** [comment]
@Narrat, some platforms use square parens and others do not. The awk script to retrieve the label assumes that they are present.

**Comment by jaromil** [comment]
Now erroring for the 'A' flag. Wow, findmnt changes **a lot** between versions. I'm wondering if this really is more reliable than reading mtab. Sure it's meant to, but really?!
```
findmnt: invalid option -- 'A'
```
I will remove this last option and include its version in `tomb --version`

**Pull request merged**
