### PR TITLE
Added tomb-qt-tray

### PR DESCRIPTION
**Pull request by mgian**
tomb-qt-tray is an equivalent of gtk-tray, only it is based on the Qt library

### CODE REVIEW

**Comment by jaromil** [comment]
excellent! can you please add a license header on each source file?
can be copied from other sources, but add your name or nickname and year

**Comment by mgian** [comment]
Added to all source files. (well, except the .ts file(s) since with the copyright notice, the linguist-qt* software don't parse them)

**Comment by jaromil** [comment]
Great, thanks! I'm testing the build and noticed it requires QT-5.4.

There should be a README.txt in extras/qt-tray to indicate requirements, but ok I can add that myself after merging the pull request.

**Comment by mgian** [comment]
Thanks. Just a quick note: my correct name is Gianluca, not Michele ;-)

**Comment by jaromil** [comment]
Oops :^) sry

**Pull request merged**
