### PR TITLE
Pitchforked sphinx integration

### LINKED ISSUE #306: Support pitchforkedsphinx for password handling
by stef, see https://github.com/stef/pitchforkedsphinx

### PR DESCRIPTION
**Pull request by heat-wave**
Fixes #306 

**Summary**:

- updated **ask_password** and adjacent logic to support retrieving password via sphinx
- added sphinx opts to commands that expect password
- added sphinx installation script (also copies default sphinx/oracle config for testing)
- created base dockerfile
- added tests for commands using sphinx

Note for the users of this feature: sphinx (client) needs to be in quiet mode to work with tomb, verbose will disrupt picking up the password properly. As suggested in sphinx's description, **do not** run sphinx and oracle on the same machine (this only gives a false feeling of security). The configuration included in extras is for testing purposes only.

### CODE REVIEW

**Comment by jaromil** [comment]
I've met @stef last weekend and noticed him about this :^)

**Comment by stef** [comment]
wow. nice work. however there is not much gained if the sphinx oracle runs on the same host as the user inputs their password. if you run both the client and the server on the same host you essentially do this: `hash(password || hash(password)^seed)` which i believe is weaker than doing a proper argon2i on the password.

**Comment by heat-wave** [comment]
Thank you @stef! I do understand that the oracle is meant to be on a different server, however for testing purposes it seemed easier to run both sphinx and oracle on the same box with tomb tests. I guess oracle could be extracted to a separate docker container and then the tests would be run by docker-compose (if jenkins supports that), but is it worth going to these lengths?

@jaromil if I may ask, does my docker config make sense (if we can complete it with loop device support)?

**Comment by stef** [comment]
oh. if this is only for testing-purposes, it is of course totally ok to do so. but in a real-life setting the two components should be separated.

**Comment by heat-wave** [comment]
Finally managed to run the tests using luks version fix (which I didn't include in the commit), summary:
- tests passing (apart from regression tests as mentioned in #343)
- changed sphinx.cfg to use fixed directory in /tmp
- updated cloakify instalalation script (since the wrapper was previously ignoring arguments)
- I haven't removed dockerfile yet; the progress of #262 looks promising so maybe I should wait until we have proper docker config and then update or reuse it

**Comment by jaromil** [comment]
Thanks for the review @stef <3 and don't worry, Tomb is all about making it easier for people to keep keys and data on separate storage supports.

**Comment by gregtzar** [comment]
@heat-wave Running a docker container as `PRIVILEGED` is one way to get loop devices working.

**Comment by heat-wave** [comment]
Finally got to iron out some issues around using sphinx under docker. Current dockerfile yields a testable image (with **docker run -it --privileged _%imagename%_ /bin/bash -c "oracle & make test"**), the only problem left is that bind-hooks test fails under docker with error "tomb [W] bind-hook target not existent". I'll look into that when I can, but I got the same error when using @gregtzar 's image to run tests on a stable Tomb release.

**Comment by heat-wave** [comment]
Alright, I got it all working. If this result is good enough, I'll pack things up into one commit and maybe tune dockerfile/travis config if you find any inconsistencies there.

**Comment by jaromil** [comment]
Awesome work. Congrats for enduring until last mile. Excellent. Tested locally and works. Please pack and then will merge. Great motivation to fix last pending bugs and make a new release. Thanks!

**Comment by heat-wave** [comment]
Thank you for the kind words! Genuinely happy to contribute.
I've packed the commits, seems ready to merge. I might not be as helpful in fixing 'real' bugs with encryption etc., but if more feature requests arise, I'll be on the lookout.

**Pull request merged**
